# Generated by Django 2.2.5 on 2019-12-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(primary_key='true', serialize=False)),
                ('workflow', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('processor', models.CharField(max_length=250)),
                ('inputPath', models.CharField(max_length=250)),
                ('outputPath', models.CharField(max_length=250)),
                ('frequency', models.PositiveIntegerField()),
            ],
        ),
    ]
