# Generated by Django 2.2.5 on 2019-12-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_auto_20191211_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('file_type', models.CharField(choices=[('.csv', 'comma separated value'), ('.xlsx', 'excel'), ('.txt', 'tab delimited')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_path', models.CharField(max_length=50)),
                ('interval', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='DBProcessor',
        ),
        migrations.DeleteModel(
            name='DBTask',
        ),
        migrations.DeleteModel(
            name='DBWorkflow',
        ),
    ]
