# Generated by Django 2.2.5 on 2020-01-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0005_auto_20191218_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='processor_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
