# Generated by Django 2.2.5 on 2020-01-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0006_workflow_processor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='version',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='message',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='task',
            name='output_file',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='workflow',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='workflow',
            name='v_input_path',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='workflow',
            name='v_output_path',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='processor',
            name='file_type',
            field=models.CharField(choices=[('.csv', 'comma separated value'), ('.xlsx', 'excel'), ('.xls', 'excel'), ('.txt', 'tab delimited')], max_length=5),
        ),
        migrations.AlterField(
            model_name='processor',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
