# Generated by Django 2.2.5 on 2020-01-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0010_auto_20200116_0846'),
        ('lims', '0008_auto_20200115_1724'),
    ]

    operations = [
    ]
