# Generated by Django 2.2.5 on 2020-01-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0011_merge_20200116_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processor',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
