version: '3.7'

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8888:80"
    links:
      - django

  django:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      - DJANGO_SETTINGS_MODULE=pylims.settings
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
    command: sh /src/django_start.sh
    volumes:
      - ./app-data:/src/app-data
    links:
      - redis
      - celery

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=pylims.settings
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
    command: celery worker -A lims.lims_celery -Q lims -l info
    volumes:
      - ./app-data:/src/app-data
    links:
      - redis

  redis:
    image: redis:latest
    hostname: redis
    expose:
      - "6379"